spring.application.name=InmobiliariaOvando

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=${JWT_SECRET}
# VER TIEMPO DE EXPIRACIÓN PARA QUE DURE UNA JORNADA DE TRABAJO
jwt.expiration-ms=${JWT_EXPIRATION_MS}